name: Healthcheck on App Ports Task8

on:
  workflow_dispatch:
  workflow_call:

jobs:
  check-access:
    runs-on: ubuntu-latest

    steps:
      - name: Check HTTP access on port 3000 (Frontend)
        run: |
          echo "ðŸ” Checking http://${{ secrets.VM_PUBLIC_IP }}:3000 ..." > access-check.log
          if curl --fail --silent http://${{ secrets.VM_PUBLIC_IP }}:3000; then
            echo "Port 3000 is accessible." >> access-check.log
          else
            echo "Port 3000 is NOT accessible." >> access-check.log
          fi

      - name: Check HTTP access on port 8080 (Backend)
        run: |
          echo "ðŸ” Checking http://${{ secrets.VM_PUBLIC_IP }}:8080 ..." >> access-check.log
          if curl --fail --silent http://${{ secrets.VM_PUBLIC_IP }}:8080; then
            echo "Port 8080 is accessible." >> access-check.log
          else
            echo "Port 8080 is NOT accessible." >> access-check.log
          fi

      - name: Upload access check log
        uses: actions/upload-artifact@v4
        with:
          name: port-access-check-log
          path: access-check.log
